name: build

on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        target:
          - x86_64-unknown-linux-gnu
          - arm-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu

    steps:
      - name: Install cross
        run: cargo install cross
      - name: Build
        run: cross build --verbose --release --target=${{ matrix.target }}
        # Note: There aren't currently any tests to run
      # - name: Run tests
      #   run: cargo test --verbose
      - name: Upload Binary
        uses: actions/upload-artifact@v3
        with:
          name: xbnet-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/xbnet

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: xbee-*
